#!/bin/bash
set -e

# Note: This is bad (dangerous) command
git config --global --add safe.directory /home/docker/chat-edge.pim.gr.jp

git config pull.rebase false
git config core.quotepath false

git -c core.sshCommand="ssh -i id_ed25519" "$*"
